apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-orders
  namespace: fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders
  template:
    metadata:
      labels:
        app: postgres-orders
    spec:
      containers:
        - name: postgres-orders
          image: postgres:17.5-alpine3.21
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fiap-ms-orders
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: postgres-storage-orders
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage-orders
          persistentVolumeClaim:
            claimName: postgres-orders-pvc
