apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
  namespace: fastfood
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: ZmlhcHRjLW9yZGVycw==   # fiaptc-orders
  SPRING_DATASOURCE_PASSWORD: ZmlhcHRjMTIzNA==       # fiaptc1234
